#pragma once

// Pami
#define I2C_SDA 0
#define I2C_SCL 1
/*
#define LEFT_MOTOR_FW_PIN 2
#define LEFT_MOTOR_RW_PIN 3
#define RIGHT_MOTOR_FW_PIN 4
#define RIGHT_MOTOR_RW_PIN 5

#define LEFT_INCREMENTAL_A_PIN 6
#define LEFT_INCREMENTAL_B_PIN 7
#define RIGHT_INCREMENTAL_A_PIN 8
#define RIGHT_INCREMENTAL_B_PIN 9
*/
/*
// Dider
#define LEFT_MOTOR_FW_PIN 14
#define LEFT_MOTOR_RW_PIN 15
#define RIGHT_MOTOR_FW_PIN 16
#define RIGHT_MOTOR_RW_PIN 17

#define LEFT_INCREMENTAL_A_PIN 4
#define LEFT_INCREMENTAL_B_PIN 5
#define RIGHT_INCREMENTAL_A_PIN 2
#define RIGHT_INCREMENTAL_B_PIN 3
*/

// Carte 2A
#define LEFT_MOTOR_FW_PIN 20
#define LEFT_MOTOR_RW_PIN 21
#define RIGHT_MOTOR_FW_PIN 27
#define RIGHT_MOTOR_RW_PIN 26

#define LEFT_INCREMENTAL_A_PIN 17
#define LEFT_INCREMENTAL_B_PIN 16
#define RIGHT_INCREMENTAL_A_PIN 19
#define RIGHT_INCREMENTAL_B_PIN 18
